"""empty message

Revision ID: 1c3bdf1bfcd8
Revises: a94bc4ea9b28
Create Date: 2019-10-14 19:35:10.461392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3bdf1bfcd8'
down_revision = 'a94bc4ea9b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Genre', ['name'])
    op.create_unique_constraint(None, 'State', ['name'])
    op.create_unique_constraint(None, 'State', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'State', type_='unique')
    op.drop_constraint(None, 'State', type_='unique')
    op.drop_constraint(None, 'Genre', type_='unique')
    # ### end Alembic commands ###
